// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addItemToCart = `-- name: AddItemToCart :one
INSERT INTO cart_items (id, user_id, product_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2
)
ON CONFLICT (user_id, product_id)
DO UPDATE SET 
    quantity = cart_items.quantity + 1,
    updated_at = NOW()
RETURNING id, created_at, updated_at, user_id, product_id, quantity
`

type AddItemToCartParams struct {
	UserID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) AddItemToCart(ctx context.Context, arg AddItemToCartParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, addItemToCart, arg.UserID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
	)
	return i, err
}

const getAllCartItems = `-- name: GetAllCartItems :many
SELECT cart_items.id, cart_items.quantity, products.name, products.price, products.id as product_id
FROM cart_items
INNER JOIN products
ON cart_items.product_id = products.id 
WHERE user_id = $1
`

type GetAllCartItemsRow struct {
	ID        uuid.UUID
	Quantity  int32
	Name      string
	Price     string
	ProductID uuid.UUID
}

func (q *Queries) GetAllCartItems(ctx context.Context, userID uuid.UUID) ([]GetAllCartItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCartItemsRow
	for rows.Next() {
		var i GetAllCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.Name,
			&i.Price,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items 
SET 
    quantity = $1,
    updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, created_at, updated_at, user_id, product_id, quantity
`

type UpdateCartItemQuantityParams struct {
	Quantity int32
	ID       uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, updateCartItemQuantity, arg.Quantity, arg.ID, arg.UserID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
	)
	return i, err
}
