// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addItemToCart = `-- name: AddItemToCart :one
INSERT INTO cart_items (id, user_id, product_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2
)
ON CONFLICT (user_id, product_id)
DO UPDATE SET 
    quantity = cart_items.quantity + 1,
    updated_at = NOW()
RETURNING id, created_at, updated_at, user_id, product_id, quantity
`

type AddItemToCartParams struct {
	UserID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) AddItemToCart(ctx context.Context, arg AddItemToCartParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, addItemToCart, arg.UserID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
	)
	return i, err
}
