// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CartItem struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

type Category struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type Order struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	UserID          uuid.UUID
	TotalAmount     string
	Status          string
	DeliveryAddress string
}

type OrderItem struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	OrderID         uuid.UUID
	ProductID       uuid.UUID
	Quantity        int32
	PriceAtPurchase string
	Status          string
}

type Product struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	Description   string
	Price         string
	StockQuantity int32
	SellerID      uuid.UUID
	CategoryID    uuid.NullUUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    uuid.UUID
}

type Seller struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	BusinessName string
	UserID       uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	FirstName      string
	LastName       string
	ContactNumber  string
	Address        sql.NullString
	Email          string
	HashedPassword string
	Role           string
}
