// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const checkAllOrderItemsConfirmed = `-- name: CheckAllOrderItemsConfirmed :one
SELECT COUNT(*) FROM order_items
WHERE order_id = $1
AND status != 'confirmed'
`

func (q *Queries) CheckAllOrderItemsConfirmed(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkAllOrderItemsConfirmed, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id, order_id, product_id, quantity, price_at_purchase)
VALUES (
    gen_random_uuid(),
    $1, 
    $2,
    $3, 
    $4
) RETURNING id, created_at, updated_at, order_id, product_id, quantity, price_at_purchase, status
`

type CreateOrderItemParams struct {
	OrderID         uuid.UUID
	ProductID       uuid.UUID
	Quantity        int32
	PriceAtPurchase string
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceAtPurchase,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtPurchase,
		&i.Status,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT order_items.id, order_items.quantity, order_items.price_at_purchase, order_items.status, products.name, products.id as product_id
FROM order_items
INNER JOIN products
ON order_items.product_id = products.id
WHERE order_id = $1
`

type GetOrderItemsRow struct {
	ID              uuid.UUID
	Quantity        int32
	PriceAtPurchase string
	Status          string
	Name            string
	ProductID       uuid.UUID
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.PriceAtPurchase,
			&i.Status,
			&i.Name,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderItemStatus = `-- name: UpdateOrderItemStatus :one
UPDATE order_items
SET 
    status = $1, 
    updated_at = NOW()
WHERE order_items.id = $2 AND order_items.order_id = $3
AND EXISTS (
    SELECT 1 FROM products p
    JOIN sellers s ON p.seller_id = s.id 
    WHERE p.id = order_items.product_id
    AND s.user_id = $4
)
RETURNING id, created_at, updated_at, order_id, product_id, quantity, price_at_purchase, status
`

type UpdateOrderItemStatusParams struct {
	Status  string
	ID      uuid.UUID
	OrderID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) UpdateOrderItemStatus(ctx context.Context, arg UpdateOrderItemStatusParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, updateOrderItemStatus,
		arg.Status,
		arg.ID,
		arg.OrderID,
		arg.UserID,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtPurchase,
		&i.Status,
	)
	return i, err
}
