// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, user_id, total_amount, delivery_address)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3
) RETURNING id, created_at, updated_at, user_id, total_amount, status, delivery_address
`

type CreateOrderParams struct {
	UserID          uuid.UUID
	TotalAmount     string
	DeliveryAddress string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.UserID, arg.TotalAmount, arg.DeliveryAddress)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.DeliveryAddress,
	)
	return i, err
}

const getOrderHistory = `-- name: GetOrderHistory :many
SELECT id, created_at, updated_at, user_id, total_amount, status, delivery_address FROM orders 
WHERE user_id = $1
`

func (q *Queries) GetOrderHistory(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrderHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.TotalAmount,
			&i.Status,
			&i.DeliveryAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders 
SET 
    status = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, created_at, updated_at, user_id, total_amount, status, delivery_address
`

type UpdateOrderStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.DeliveryAddress,
	)
	return i, err
}
