// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, description, price, stock_quantity, seller_id, category_id) 
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, created_at, updated_at, name, description, price, stock_quantity, seller_id, category_id
`

type CreateProductParams struct {
	Name          string
	Description   string
	Price         string
	StockQuantity int32
	SellerID      uuid.UUID
	CategoryID    uuid.NullUUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StockQuantity,
		arg.SellerID,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.SellerID,
		&i.CategoryID,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1 AND seller_id = $2
`

type DeleteProductParams struct {
	ID       uuid.UUID
	SellerID uuid.UUID
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, arg.ID, arg.SellerID)
	return err
}

const getAllProductsBySeller = `-- name: GetAllProductsBySeller :many
SELECT id, created_at, updated_at, name, description, price, stock_quantity, seller_id, category_id FROM products
WHERE seller_id = $1
LIMIT $2 OFFSET $3
`

type GetAllProductsBySellerParams struct {
	SellerID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetAllProductsBySeller(ctx context.Context, arg GetAllProductsBySellerParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductsBySeller, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.StockQuantity,
			&i.SellerID,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductDetails = `-- name: UpdateProductDetails :one
UPDATE products
SET 
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    price = COALESCE($5, price),
    stock_quantity = COALESCE($6, stock_quantity),
    updated_at = NOW()
WHERE id = $1 AND seller_id = $2
RETURNING id, created_at, updated_at, name, description, price, stock_quantity, seller_id, category_id
`

type UpdateProductDetailsParams struct {
	ID            uuid.UUID
	SellerID      uuid.UUID
	Name          sql.NullString
	Description   sql.NullString
	Price         sql.NullString
	StockQuantity sql.NullInt32
}

func (q *Queries) UpdateProductDetails(ctx context.Context, arg UpdateProductDetailsParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductDetails,
		arg.ID,
		arg.SellerID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StockQuantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.SellerID,
		&i.CategoryID,
	)
	return i, err
}
