// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, description, price, stock_quantity, seller_id, category_id) 
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, created_at, updated_at, name, description, price, stock_quantity, seller_id, category_id
`

type CreateProductParams struct {
	Name          string
	Description   string
	Price         string
	StockQuantity int32
	SellerID      uuid.UUID
	CategoryID    uuid.NullUUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StockQuantity,
		arg.SellerID,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.SellerID,
		&i.CategoryID,
	)
	return i, err
}
