// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sellers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createSeller = `-- name: CreateSeller :one
INSERT INTO sellers (id, business_name, user_id) 
VALUES (
    gen_random_uuid(),
    $1,
    $2
) RETURNING id, created_at, updated_at, business_name, user_id
`

type CreateSellerParams struct {
	BusinessName string
	UserID       uuid.UUID
}

func (q *Queries) CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error) {
	row := q.db.QueryRowContext(ctx, createSeller, arg.BusinessName, arg.UserID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BusinessName,
		&i.UserID,
	)
	return i, err
}

const getSellerByUserID = `-- name: GetSellerByUserID :one
SELECT id, created_at, updated_at, business_name, user_id FROM sellers 
WHERE user_id = $1
`

func (q *Queries) GetSellerByUserID(ctx context.Context, userID uuid.UUID) (Seller, error) {
	row := q.db.QueryRowContext(ctx, getSellerByUserID, userID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BusinessName,
		&i.UserID,
	)
	return i, err
}
