// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, first_name, last_name, contact_number, email, hashed_password)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, created_at, updated_at, first_name, last_name, contact_number, address, email, hashed_password, role
`

type CreateUserParams struct {
	FirstName      string
	LastName       string
	ContactNumber  string
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.ContactNumber,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.ContactNumber,
		&i.Address,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, first_name, last_name, contact_number, address, email, hashed_password, role FROM users 
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.ContactNumber,
		&i.Address,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
	)
	return i, err
}

const updateUserDetails = `-- name: UpdateUserDetails :one
UPDATE users 
SET 
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    contact_number = COALESCE($4, contact_number),
    address = COALESCE($5, address),
    email = COALESCE($6, email),
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, first_name, last_name, contact_number, address, email, hashed_password, role
`

type UpdateUserDetailsParams struct {
	ID            uuid.UUID
	FirstName     sql.NullString
	LastName      sql.NullString
	ContactNumber sql.NullString
	Address       sql.NullString
	Email         sql.NullString
}

func (q *Queries) UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserDetails,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.ContactNumber,
		arg.Address,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.ContactNumber,
		&i.Address,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
	)
	return i, err
}
