// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, first_name, last_name, contact_number, email, hashed_password)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, created_at, updated_at, first_name, last_name, contact_number, address, email, hashed_password, role
`

type CreateUserParams struct {
	FirstName      string
	LastName       string
	ContactNumber  string
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.ContactNumber,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.ContactNumber,
		&i.Address,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
	)
	return i, err
}
